### ISSUE TITLE
Download link broken

### ISSUE THREAD

**Issue by JohanMabille** [marehr/intel-sde-downloader#10]
It looks like the download page has moved [here](https://software.intel.com/content/www/us/en/develop/articles/pre-release-license-agreement-for-intel-software-development-emulator-accept-end-user-license-agreement-and-download.html).

I also noticed that you can directly download the tarball (by getting the link from the js source) without accepting the license (which is probably a bug I guess).

**Comment by marehr** [comment]
Thank you, I will try to figure out if the approach with mechanical soup is still working if they now use javascript. I hope that the javascript is only used unnecessarily and I still can access the DOM without modifying it by some dynamic parts.

And yes I guess it is a bug; but if they don't fix it it might be the better approach to download it directly :smile: 

AFAIK you can download the intel-compiler directly by some URL so maybe they finally fixed that forced license BS.
